M48
; DRILL file KiCad 10.0.1 date 2026-05-26T19:56:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-26T19:56:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.3465Y-2.3622
X3.3465Y-4.7244
X6.5945Y-2.3622
X6.5945Y-4.7244
M30
